spring:
  application:
    name: yoke-event
  profiles:
    active: docker

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create


  datasource:
    platform: postgres
    url: jdbc:postgresql://db-postgres:5432/postgres
    username: postgres
    password: '{cipher}98052f6f3c5fc384666482cd9e6a3faf8f4ffe182d55e42ebeb4d0e674d91ac6'

  cloud:
    stream:
      bindings:
        createEvent:
          destination: yoke-create-event
          producer:
            partition-count: 3
        deleteEvent:
          destination: yoke-delete-event
          producer:
            partition-count: 3

      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true

server:
  port: 8083

yoke:
  notify:
    url: http://YOKE-NOTIFY/event